###################################
#+===============================+#
#|+=============================+|#
#||                             ||#
#||      mcMMOLevelPrefix       ||#
#||            by               ||#
#||      GrimReaper52498        ||#
#||                             ||#
#|+=============================+|#
#+===============================+#
###################################

Bracket-Color: '&8'
Number-Color: '&6'